"""user_id NOT NULL on user-owned tables

Revision ID: f6ce2dbad4ac
Revises: 5d7e93f6a306
Create Date: 2026-07-05 18:46:51.364770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ce2dbad4ac'
down_revision: Union[str, Sequence[str], None] = '5d7e93f6a306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_USER_TABLES = (
    "backtest_runs", "cash_flows", "holdings", "screener_scores",
    "transactions", "wallet", "watchlist",
)


def upgrade() -> None:
    """Upgrade schema."""
    # Safety net before enforcing NOT NULL: assign any legacy pre-multi-user rows
    # (user_id IS NULL) to the bootstrap owner. No-op on a DB that was always
    # multi-user — every row is already stamped — which includes this project's
    # live DB. 'local@localhost' is db/session.py's BOOTSTRAP_EMAIL.
    for _t in _USER_TABLES:
        op.execute(
            f"UPDATE {_t} SET user_id = "
            "(SELECT id FROM users WHERE email = 'local@localhost') "
            "WHERE user_id IS NULL"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('screener_scores', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('screener_scores', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
